#' generateCathKeyDF.R
#' 
#'  \code{generateCathKeyDF} is a function in the Nh3D2.0 package. It generates
#'  a hierarchial database containing all CATH domains and descriptions for
#'  the user as a reference. 
#' 
#' @param cathTable (data.frame) A dataframe that contains the CATH data. Can
#' be generated by calling the \code{generateCathTable()} function.
#' 
#' @return A dataframe containing the hierarchial data of the CATH database
#' and the corresponding descriptions to each domain.
#' 
#' @examples
#' \dontrun{
#' 
#' # Generate the cathTable
#' cathTable <- generateCathTable()
#' 
#' # Make the key dataframe
#' cathKeyDF <- generateCathKeyDF(cathTable)
#' 
#' (cathKeyDF)
#' 
#' }
#' 
#' @export

generateCathKeyDF <- function(cathTable) {
  
  if (missing(cathTable)) {
    stop("Please provide the CATH table as a parameter. It can be
         generated by running generateCathTable() or updateCath().")
  }
  
  # Call helper function to read cath name data
  cathNames <- readCathNames()
  
  # Generate a relational database containing the hierarchy data
  # for the cath database
  # Organize by class, architecture, topology and homology groups
  
  cathGroupDF <- list()
  
  # Set Class categories
  cathGroupDF$Class <- cathNames[cathNames$Category %in% unique(cathTable$V2),]
  colnames(cathGroupDF$Class)[1] <- "ClassID"
  
  # Set Architecture categories
  uniqueA <- unique(paste(cathTable$V2, ".", cathTable$V3, sep = ""))
  
  cathGroupDF$Architecture <- cathNames[cathNames$Category %in% uniqueA,]
  colnames(cathGroupDF$Architecture)[1] <- "ArchitectureID"
  cathGroupDF$Architecture$ClassID <- sub("\\..*", "", 
                                        cathGroupDF$Architecture$ArchitectureID)
  
  # Set Topology categories
  uniqueT <- unique(paste(cathTable$V2, ".", cathTable$V3, ".", cathTable$V4,
                          sep = ""))
  cathGroupDF$Topology <- cathNames[cathNames$Category %in% uniqueT,]
  colnames(cathGroupDF$Topology)[1] <- "TopologyID"
  cathGroupDF$Topology$ArchitectureID <- sub( "(^[^.]+[.][^.]+)(.+$)", "\\1",
                                              cathGroupDF$Topology$TopologyID)
  
  # Set Homology categories
  uniqueH <- unique(paste(cathTable$V2, ".", cathTable$V3, ".", cathTable$V4, ".",
                          cathTable$V5, sep = ""))
  
  cathGroupDF$Homology <- cathNames[cathNames$Category %in% uniqueH,]
  colnames(cathGroupDF$Homology)[1] <- "HomologyID"
  cathGroupDF$Homology$TopologyID <- sub( "(^[^.]+[.][^.]+[.][^.]+)(.+$)", "\\1",
                                              cathGroupDF$Homology$HomologyID)
  
  return(cathGroupDF)

}



#[END]

