#'Nh3D.R
#
# Purpose: Non-Homologous protein dataset based off the CATH database. 
# A BCB430 course project
# Version: 1.0.0
# Version history: 1.0.0
# Date: March 24 2019
# Author: Heewon Lee (heewon.lee@mail.utoronto.ca)
# License: MIT
#
#  Output: A dataframe containing the best representative PDB domains in each
#  homology group according to the CATH database.
#  Dependencies: BiocManager, Biostrings, msa
#

#' \code{Nh3D} is the main function to Nh3D2.0.
#' Calling this function will generate a dataset with the best representatives
#' for each topology group where all homologies in each group are non-homologous.
#' It calls several helper functions in order to generate the database.
#' 
#' @param cathTable (data.frame) A dataframe that contains the CATH data. Can
#' be generated by calling the \code{generateCathTable()} function.
#' 
#' @param class (numeric) The class identifier of a class of interest. The
#' class identifier must be provided to reduce processing times.
#' 
#' @param architecture (numeric) The architecture identifier in the CATH
#' database. Automatically set to NULL.
#' 
#' @param topology (numeric) A topology identifier from the CATH database. 
#' Automatically set to NULL.
#' 
#' @param homology (numeric) A homology identifier from the CATH database. 
#' Automatically set to NULL.
#' 
#' @return A dataframe containing the best representative PDB domains in a specified
#' CATH group according to the CATH database.
#' 
#' @examples
#' \dontrun{
#'  
#' # We first generate a cathTable in our local global env.
#' cathTable <- generateCathTable()
#'  
#' # We then select a topology group that we would like to retrieve a dataset of
#' # non-homologous proteins for. 
#' 
#' class <- 1
#' architecture <- 10
#' topology <- 220
#' 
#' # Run Nh3D with the parameters
#' myTable <- Nh3D(cathTable, class  = class, architecture = architecture, 
#' topology = topology)
#' 
#' (myTable)
#' 
#' }
#'
#' @export

Nh3D <- function(cathTable, class, architecture = NULL, topology = NULL, 
                 homology = NULL) {
  
  # Check if parameters exist
  if (is.null(cathTable)) {
    stop("Please run generateCathTable() and input the saved dataframe into the
         parameter for cathTable.")
    
  }
  
  if (is.null(class)) {
    stop("Please provide a CATH class identifier that you would like to retrieve 
         the non-homologous 3D protein set for. All identifiers are provided
         in the reuslting dataframe from the generateCathKeyDF() function.")
    
  }
  
  # Select the domains within the Cath table identifiers
  selCathTable <- cathTable[cathTable$V2 == class,]
  
  if (!is.null(architecture)) {
    selCathTable <- selCathTable[selCathTable$V3 == architecture,]
  }
  
  if (!is.null(topology)) {
    selCathTable <- selCathTable[selCathTable$V4 == topology,]
  }
  
  if (!is.null(homology)) {
    selCathTable <- selCathTable[selCathTable$V5 == homology,]
  }
  
  selCathTable <- addCathCat(selCathTable)
  
  message("Retrieving RFactor data from the PDB...")
  #Fetch R factor data from PDB fetch services for each protein in the 
  #generated cathtable
  selCathTable <- fetchRFactor(selCathTable)
  
  # Remove lowest resolutions
  selCathTable <- removeLowestResolution(selCathTable)
  
  # Retrieve stereochemical verification data
  message("Retrieving stereochemical verification data. This
          will take a couple minutes...")
  selCathTable <- fetchVerifyData(selCathTable)

  
  # Add the missing R values
  selCathTable <- fixMissingRValues(selCathTable)
  
  # Weight the entries
  message("Weighting PDB entries...")
  selCathTable <- weightHomologies(selCathTable)

  message("Successfully generated the non homologous data
          set!")
  
  return (selCathTable)
}

#[END]

